// <auto-generated />
using System;
using EShopy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShopy.Infrastructure.Migrations
{
    [DbContext(typeof(EShopyDbContext))]
    [Migration("20260221000601_AddStoreIdToProducts")]
    partial class AddStoreIdToProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.3.25171.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShopy.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del producto.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creacion en UTC.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que creo el registro.");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasComment("Codigo ISO 4217 de moneda.");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON para extensiones no criticas.");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Descripcion larga del producto.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre visible del producto.");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Precio unitario del producto.");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Token de concurrencia optimista.");

                    b.Property<string>("Sku")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("SKU opcional del producto (normalizado a mayusculas).");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Slug publico del producto (SEO).");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("Estado del producto (0=Draft,1=Active,2=Archived).");

                    b.Property<int>("StockOnHand")
                        .HasColumnType("int")
                        .HasComment("Stock simple disponible.");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Store al que pertenece el producto (FK a Stores).");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del tenant propietario.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultima actualizacion en UTC.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que actualizo el registro.");

                    b.HasKey("Id")
                        .HasName("PK_Products");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("IX_Products_TenantId_Name");

                    b.HasIndex("TenantId", "Sku")
                        .HasDatabaseName("UQ_Products_TenantId_Sku")
                        .HasFilter("[Sku] IS NOT NULL");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_Products_TenantId_Slug");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Products_TenantId_Status");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasComment("Catalogo de productos por tenant.");

                            t.HasCheckConstraint("CK_Products_Price_Positive", "[Price] >= 0");

                            t.HasCheckConstraint("CK_Products_Stock_NonNegative", "[StockOnHand] >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
