// <auto-generated />
using System;
using EShopy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShopy.Infrastructure.Migrations
{
    [DbContext(typeof(EShopyDbContext))]
    [Migration("20260726205016_AddAuditLogs")]
    partial class AddAuditLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.3.25171.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShopy.Domain.Carts.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del carrito.");

                    b.Property<string>("CartToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("UUID generado en el frontend.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creacion en UTC.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que creo el registro.");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON para extensiones no criticas.");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Se extiende con cada actividad. Para limpieza de carritos abandonados (F6-04).");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Token de concurrencia optimista.");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del tenant propietario.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultima actualizacion en UTC.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que actualizo el registro.");

                    b.HasKey("Id")
                        .HasName("PK_Carts");

                    b.HasIndex("TenantId", "CartToken")
                        .IsUnique()
                        .HasDatabaseName("UQ_Carts_TenantId_CartToken");

                    b.ToTable("Carts", null, t =>
                        {
                            t.HasComment("Carrito server-side, previo al checkout.");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Carts.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del item.");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Carrito al que pertenece.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creacion en UTC.");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Producto referenciado (FK a Products).");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Cantidad. Acumula si el producto se agrega de nuevo, no duplica fila.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultima actualizacion en UTC.");

                    b.HasKey("Id")
                        .HasName("PK_CartItems");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UQ_CartItems_CartId_ProductId");

                    b.ToTable("CartItems", null, t =>
                        {
                            t.HasComment("Items de un carrito. Un producto, una fila — sin snapshot de precio.");

                            t.HasCheckConstraint("CK_CartItems_Quantity_Positive", "[Quantity] >= 1");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Common.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del registro.");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Modulo.Operacion, ej. 'Order.ChangeStatus'.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de la accion en UTC.");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Texto libre con el detalle de la accion (ej. cambio de estado). No es JSON estructurado a proposito — YAGNI hasta que un caso de uso real lo pida.");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id de la entidad afectada.");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Tipo de entidad afectada, ej. 'Order'.");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Tenant afectado por la accion. Nullable: hay acciones a nivel plataforma (ej. activacion de tenant via SUPERADMIN).");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Email del usuario autenticado. Null si no hay usuario autenticado.");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Id del usuario autenticado que ejecuto la accion. Null si no hay usuario autenticado (ej. webhook).");

                    b.HasKey("Id")
                        .HasName("PK_AuditLogs");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_EntityType_EntityId");

                    b.HasIndex("TenantId", "CreatedAtUtc")
                        .HasDatabaseName("IX_AuditLogs_TenantId_CreatedAtUtc");

                    b.ToTable("AuditLogs", null, t =>
                        {
                            t.HasComment("Registro append-only de operaciones sensibles (F9-03). Nunca se actualiza ni se borra.");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Common.Counters.TenantCounter", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del tenant propietario.");

                    b.Property<string>("CounterType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Tipo de contador (ej. 'OrderNumber').");

                    b.Property<int>("CurrentValue")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasComment("Valor actual del contador. Concurrency token EF — sin SQL crudo.");

                    b.HasKey("TenantId", "CounterType")
                        .HasName("PK_TenantCounters");

                    b.ToTable("TenantCounters", null, t =>
                        {
                            t.HasComment("Contadores atomicos por tenant (ej. secuencia de OrderNumber).");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del pedido.");

                    b.Property<string>("BuyerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Email del comprador al momento del checkout.");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre del comprador al momento del checkout.");

                    b.Property<string>("CartToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("CartToken del carrito origen.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creacion en UTC.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que creo el registro.");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasComment("Heredado del Store al momento del checkout.");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON para extensiones no criticas.");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int")
                        .HasComment("Secuencial por tenant. Asignado atomicamente por ICheckoutWriter, no en la creacion.");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Referencia al Payment activo. Sin FK enforced (ver Payment.OrderId).");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Token de concurrencia optimista.");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Direccion de entrega.");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("Estado del pedido (0=PendingPayment,1=Paid,2=Cancelled,3=Refunded).");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Store al que pertenece el pedido.");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del tenant propietario.");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Suma de OrderItems, calculado al crear.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultima actualizacion en UTC.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que actualizo el registro.");

                    b.HasKey("Id")
                        .HasName("PK_Orders");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId", "BuyerEmail")
                        .HasDatabaseName("IX_Orders_TenantId_BuyerEmail");

                    b.HasIndex("TenantId", "OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Orders_TenantId_OrderNumber");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Orders_TenantId_Status");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasComment("Pedido generado desde checkout.");

                            t.HasCheckConstraint("CK_Orders_TotalAmount_NonNegative", "[TotalAmount] >= 0");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del item.");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Pedido al que pertenece.");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Producto referenciado (FK a Products). Referencia historica, no se borra si el producto se archiva.");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Snapshot del nombre al momento del checkout.");

                    b.Property<string>("ProductSku")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("Snapshot del SKU al momento del checkout.");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Cantidad del item.");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Snapshot del precio unitario al momento del checkout.");

                    b.HasKey("Id")
                        .HasName("PK_OrderItems");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", null, t =>
                        {
                            t.HasComment("Snapshot inmutable de un producto al momento del checkout.");

                            t.HasCheckConstraint("CK_OrderItems_Quantity_Positive", "[Quantity] >= 1");

                            t.HasCheckConstraint("CK_OrderItems_UnitPrice_NonNegative", "[UnitPrice] >= 0");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del pago.");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Monto de la transaccion.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creacion en UTC.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que creo el registro.");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasComment("Heredado del Store.");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON para extensiones no criticas.");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Codigo de error del provider si fallo.");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Mensaje de error del provider si fallo.");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Pedido al que pertenece (FK a Orders).");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Provider de pago (ej. 'bancard', 'pagopar', 'fake').");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Id de la transaccion en el provider.");

                    b.Property<string>("ProviderPaymentUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("URL de pago devuelta al frontend.");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Token de concurrencia optimista.");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("Estado del pago (0=Initiated,1=Authorized,2=Captured,3=Failed,4=Refunded).");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del tenant propietario.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultima actualizacion en UTC.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que actualizo el registro.");

                    b.HasKey("Id")
                        .HasName("PK_Payments");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Payments_OrderId");

                    b.HasIndex("Provider", "ProviderPaymentId")
                        .HasDatabaseName("IX_Payments_Provider_ProviderPaymentId")
                        .HasFilter("[ProviderPaymentId] IS NOT NULL");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasComment("Intento de pago asociado a un Order.");

                            t.HasCheckConstraint("CK_Payments_Amount_NonNegative", "[Amount] >= 0");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Payments.PaymentEventProcessed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del registro.");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Id del evento segun el provider.");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de procesamiento en UTC.");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Provider de pago que emitio el evento.");

                    b.HasKey("Id")
                        .HasName("PK_PaymentEventsProcessed");

                    b.HasIndex("Provider", "EventId")
                        .IsUnique()
                        .HasDatabaseName("UQ_PaymentEventsProcessed_Provider_EventId");

                    b.ToTable("PaymentEventsProcessed", null, t =>
                        {
                            t.HasComment("Ledger de idempotencia de webhooks de pago. Global, no multi-tenant: (Provider, EventId) ya es unico a nivel provider.");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del producto.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creacion en UTC.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que creo el registro.");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasComment("Codigo ISO 4217 de moneda.");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON para extensiones no criticas.");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Descripcion larga del producto.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre visible del producto.");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Precio unitario del producto.");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Token de concurrencia optimista.");

                    b.Property<string>("Sku")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("SKU opcional del producto (normalizado a mayusculas).");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Slug publico del producto (SEO).");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("Estado del producto (0=Draft,1=Active,2=Archived).");

                    b.Property<int>("StockOnHand")
                        .HasColumnType("int")
                        .HasComment("Stock simple disponible.");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Store al que pertenece el producto (FK a Stores).");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del tenant propietario.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultima actualizacion en UTC.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que actualizo el registro.");

                    b.HasKey("Id")
                        .HasName("PK_Products");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("IX_Products_TenantId_Name");

                    b.HasIndex("TenantId", "Sku")
                        .HasDatabaseName("UQ_Products_TenantId_Sku")
                        .HasFilter("[Sku] IS NOT NULL");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_Products_TenantId_Slug");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Products_TenantId_Status");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasComment("Catalogo de productos por tenant.");

                            t.HasCheckConstraint("CK_Products_Price_Positive", "[Price] >= 0");

                            t.HasCheckConstraint("CK_Products_Stock_NonNegative", "[StockOnHand] >= 0");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico de la suscripcion.");

                    b.Property<DateTime>("BillingCycleEnd")
                        .HasColumnType("datetime2")
                        .HasComment("Fin del ciclo de facturacion actual.");

                    b.Property<DateTime>("BillingCycleStart")
                        .HasColumnType("datetime2")
                        .HasComment("Inicio del ciclo de facturacion actual.");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de cancelacion, si aplica.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creacion en UTC.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que creo el registro.");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasComment("Codigo ISO 4217 de moneda del cobro.");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON para extensiones no criticas.");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Id en la plataforma de billing externa (Fase 8).");

                    b.Property<byte>("Plan")
                        .HasColumnType("tinyint")
                        .HasComment("Plan contratado (0=Basic,1=Gold,2=Diamond).");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Precio del plan al momento de la suscripcion.");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Token de concurrencia optimista.");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("Estado (0=PendingActivation,1=Active,2=PastDue,3=Suspended,4=Cancelled).");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del tenant propietario.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultima actualizacion en UTC.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que actualizo el registro.");

                    b.HasKey("Id")
                        .HasName("PK_Subscriptions");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Subscriptions_TenantId_NonCancelled")
                        .HasFilter("[Status] <> 4");

                    b.ToTable("Subscriptions", null, t =>
                        {
                            t.HasComment("Suscripcion mensual del tenant a un plan.");

                            t.HasCheckConstraint("CK_Subscriptions_PriceAmount_NonNegative", "[PriceAmount] >= 0");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Tenants.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del store.");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasComment("Color de fondo en hex.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creacion en UTC.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que creo el registro.");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasComment("Codigo ISO 4217 de moneda. Heredado por Products y Orders.");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON para extensiones no criticas.");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Descripcion publica de la tienda.");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("URL del logo de la tienda.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre publico de la tienda.");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasComment("Color primario de marca en hex, ej. '#FF5733'.");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Token de concurrencia optimista.");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del tenant propietario.");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Timezone IANA de la tienda, ej. 'America/Asuncion'.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultima actualizacion en UTC.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que actualizo el registro.");

                    b.HasKey("Id")
                        .HasName("PK_Stores");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Stores_TenantId");

                    b.ToTable("Stores", null, t =>
                        {
                            t.HasComment("Configuracion de tienda por tenant. 1:1 con Tenant en MVP.");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del tenant.");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha en que paso a Active por primera vez.");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre legal del negocio.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de alta en UTC.");

                    b.Property<byte>("Plan")
                        .HasColumnType("tinyint")
                        .HasComment("Plan contratado (0=Basic,1=Gold,2=Diamond).");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("Estado del tenant (0=PendingPayment,1=Active,2=Suspended,3=Cancelled).");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Subdominio unico en toda la plataforma.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultimo cambio de estado en UTC.");

                    b.HasKey("Id")
                        .HasName("PK_Tenants");

                    b.HasIndex("Subdomain")
                        .IsUnique()
                        .HasDatabaseName("UQ_Tenants_Subdomain");

                    b.ToTable("Tenants", null, t =>
                        {
                            t.HasComment("Tenants de la plataforma. Entidad global, no multi-tenant.");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Tenants.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del usuario.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creacion en UTC.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que creo el registro.");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON para extensiones no criticas.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Email del usuario. Unico por tenant.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasComment("Permite deshabilitar el acceso sin eliminar el registro.");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Id del usuario en Keycloak.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre visible del usuario.");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint")
                        .HasComment("Rol del usuario (0=Owner,1=Admin,2=Staff).");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Token de concurrencia optimista.");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del tenant propietario.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultima actualizacion en UTC.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que actualizo el registro.");

                    b.HasKey("Id")
                        .HasName("PK_TenantUsers");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_TenantUsers_TenantId_Email");

                    b.ToTable("TenantUsers", null, t =>
                        {
                            t.HasComment("Usuarios con acceso al panel de administracion de un tenant.");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Carts.CartItem", b =>
                {
                    b.HasOne("EShopy.Domain.Carts.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShopy.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Products_ProductId");
                });

            modelBuilder.Entity("EShopy.Domain.Orders.Order", b =>
                {
                    b.HasOne("EShopy.Domain.Tenants.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Stores_StoreId");
                });

            modelBuilder.Entity("EShopy.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("EShopy.Domain.Orders.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShopy.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItems_Products_ProductId");
                });

            modelBuilder.Entity("EShopy.Domain.Payments.Payment", b =>
                {
                    b.HasOne("EShopy.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Orders_OrderId");
                });

            modelBuilder.Entity("EShopy.Domain.Products.Product", b =>
                {
                    b.HasOne("EShopy.Domain.Tenants.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Products_Stores_StoreId");

                    b.HasOne("EShopy.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Products_Tenants_TenantId");
                });

            modelBuilder.Entity("EShopy.Domain.Carts.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EShopy.Domain.Orders.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
