// <auto-generated />
using System;
using EShopy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShopy.Infrastructure.Migrations
{
    [DbContext(typeof(EShopyDbContext))]
    [Migration("20260726164030_AddTenantsStoresSubscriptions")]
    partial class AddTenantsStoresSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.3.25171.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShopy.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del producto.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creacion en UTC.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que creo el registro.");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasComment("Codigo ISO 4217 de moneda.");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON para extensiones no criticas.");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Descripcion larga del producto.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre visible del producto.");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Precio unitario del producto.");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Token de concurrencia optimista.");

                    b.Property<string>("Sku")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("SKU opcional del producto (normalizado a mayusculas).");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Slug publico del producto (SEO).");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("Estado del producto (0=Draft,1=Active,2=Archived).");

                    b.Property<int>("StockOnHand")
                        .HasColumnType("int")
                        .HasComment("Stock simple disponible.");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Store al que pertenece el producto (FK a Stores).");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del tenant propietario.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultima actualizacion en UTC.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que actualizo el registro.");

                    b.HasKey("Id")
                        .HasName("PK_Products");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("IX_Products_TenantId_Name");

                    b.HasIndex("TenantId", "Sku")
                        .HasDatabaseName("UQ_Products_TenantId_Sku")
                        .HasFilter("[Sku] IS NOT NULL");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_Products_TenantId_Slug");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Products_TenantId_Status");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasComment("Catalogo de productos por tenant.");

                            t.HasCheckConstraint("CK_Products_Price_Positive", "[Price] >= 0");

                            t.HasCheckConstraint("CK_Products_Stock_NonNegative", "[StockOnHand] >= 0");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico de la suscripcion.");

                    b.Property<DateTime>("BillingCycleEnd")
                        .HasColumnType("datetime2")
                        .HasComment("Fin del ciclo de facturacion actual.");

                    b.Property<DateTime>("BillingCycleStart")
                        .HasColumnType("datetime2")
                        .HasComment("Inicio del ciclo de facturacion actual.");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de cancelacion, si aplica.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creacion en UTC.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que creo el registro.");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasComment("Codigo ISO 4217 de moneda del cobro.");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON para extensiones no criticas.");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Id en la plataforma de billing externa (Fase 8).");

                    b.Property<byte>("Plan")
                        .HasColumnType("tinyint")
                        .HasComment("Plan contratado (0=Basic,1=Gold,2=Diamond).");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Precio del plan al momento de la suscripcion.");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Token de concurrencia optimista.");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("Estado (0=PendingActivation,1=Active,2=PastDue,3=Suspended,4=Cancelled).");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del tenant propietario.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultima actualizacion en UTC.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que actualizo el registro.");

                    b.HasKey("Id")
                        .HasName("PK_Subscriptions");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Subscriptions_TenantId_NonCancelled")
                        .HasFilter("[Status] <> 4");

                    b.ToTable("Subscriptions", null, t =>
                        {
                            t.HasComment("Suscripcion mensual del tenant a un plan.");

                            t.HasCheckConstraint("CK_Subscriptions_PriceAmount_NonNegative", "[PriceAmount] >= 0");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Tenants.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del store.");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasComment("Color de fondo en hex.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creacion en UTC.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que creo el registro.");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasComment("Codigo ISO 4217 de moneda. Heredado por Products y Orders.");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON para extensiones no criticas.");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Descripcion publica de la tienda.");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("URL del logo de la tienda.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre publico de la tienda.");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasComment("Color primario de marca en hex, ej. '#FF5733'.");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Token de concurrencia optimista.");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del tenant propietario.");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Timezone IANA de la tienda, ej. 'America/Asuncion'.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultima actualizacion en UTC.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que actualizo el registro.");

                    b.HasKey("Id")
                        .HasName("PK_Stores");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Stores_TenantId");

                    b.ToTable("Stores", null, t =>
                        {
                            t.HasComment("Configuracion de tienda por tenant. 1:1 con Tenant en MVP.");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del tenant.");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha en que paso a Active por primera vez.");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre legal del negocio.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de alta en UTC.");

                    b.Property<byte>("Plan")
                        .HasColumnType("tinyint")
                        .HasComment("Plan contratado (0=Basic,1=Gold,2=Diamond).");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("Estado del tenant (0=PendingPayment,1=Active,2=Suspended,3=Cancelled).");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Subdominio unico en toda la plataforma.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultimo cambio de estado en UTC.");

                    b.HasKey("Id")
                        .HasName("PK_Tenants");

                    b.HasIndex("Subdomain")
                        .IsUnique()
                        .HasDatabaseName("UQ_Tenants_Subdomain");

                    b.ToTable("Tenants", null, t =>
                        {
                            t.HasComment("Tenants de la plataforma. Entidad global, no multi-tenant.");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Tenants.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador unico del usuario.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creacion en UTC.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que creo el registro.");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON para extensiones no criticas.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Email del usuario. Unico por tenant.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasComment("Permite deshabilitar el acceso sin eliminar el registro.");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Id del usuario en Keycloak.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre visible del usuario.");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint")
                        .HasComment("Rol del usuario (0=Owner,1=Admin,2=Staff).");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Token de concurrencia optimista.");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del tenant propietario.");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de ultima actualizacion en UTC.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Usuario/actor que actualizo el registro.");

                    b.HasKey("Id")
                        .HasName("PK_TenantUsers");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_TenantUsers_TenantId_Email");

                    b.ToTable("TenantUsers", null, t =>
                        {
                            t.HasComment("Usuarios con acceso al panel de administracion de un tenant.");
                        });
                });

            modelBuilder.Entity("EShopy.Domain.Products.Product", b =>
                {
                    b.HasOne("EShopy.Domain.Tenants.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Products_Stores_StoreId");

                    b.HasOne("EShopy.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Products_Tenants_TenantId");
                });
#pragma warning restore 612, 618
        }
    }
}
